#include QMK_KEYBOARD_H

/* THIS FILE WAS GENERATED!
 *
 * This file was generated by qmk json2c. You may or may not want to
 * edit it directly.
 */

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
	[0] = LAYOUT_ergodox(KC_TILD, KC_1, KC_2, KC_3, KC_4, KC_5, KC_ESC, KC_TAB, KC_QUOT, KC_COMM, KC_DOT, KC_P, KC_Y, KC_NO, KC_LSFT, KC_A, KC_O, KC_E, KC_U, KC_I, KC_LALT, KC_S, KC_Q, KC_J, KC_K, KC_X, KC_NO, KC_LALT, KC_GRV, KC_NO, KC_BSLS, KC_SLSH, KC_LGUI, KC_HOME, KC_END, KC_BSPC, KC_LCTL, KC_LALT, KC_NO, KC_6, KC_7, KC_8, KC_9, KC_0, KC_MINS, KC_NO, KC_F, KC_G, KC_C, KC_R, KC_L, KC_EQL, KC_D, KC_H, KC_T, KC_N, KC_S, KC_NO, KC_NO, KC_B, KC_M, KC_W, KC_V, KC_Z, KC_NO, KC_LBRC, KC_RBRC, KC_MINS, KC_NO, KC_NO, KC_PGUP, KC_RCTL, KC_PGDN, KC_NO, KC_ENT, KC_SPC)
};
